#%RAML 1.0 NamedExample
 
        [ {
                  "username": "john",
                  "userId": 1234,
                  "orderId": 67889,
                  "email": "xemail@email.com"
                },
             {
                  "username": "Smith",
                  "userId": 1378,
                  "orderId": 65743,
                  "email": "email@email.com"
                } ]