#%RAML 1.0 NamedExample

[
       {
        "userId": 900,
        "email": "abcdkkk@gmail.com",
        "productId": 1573012800000,
        "orderId": 1582747201000,
        "category": 1,
        "deleted": false,
        "username": "Abc"
      },
      {
        "userId": 1000,
        "email": "Betty@gmail.com",
        "date_joined": 1589068800000,
        "orderId": 1586044800000,
        "category": 5,
        "deleted": false,
        "username": "Cristina"
      } 
]

