#%RAML 1.0 NamedExample
          { 
        "userId": 900,
        "email": "abcdkkk@gmail.com",
        "productId": 1573012800000,
        "orderId": 1582747201000,
        "categoryid": 1,
        "deleted": false,
        "username": "Abc"
                }