#%RAML 1.0 DocumentationItem
title: online shopping API documentation info
content: This REST API contains several http status code responses

documentation:
  - title: general description በአማርኛ ነው
  - content: |
      ይሄ የኤፒአይ ዶኩመንት የያዘው ስለ ዩዘሮች : ኦርደርስ ፡ ፕሮዱክቶች ፡ ካታጎሪስ ነው
  - title: ዩዘሮች
  - content: |
      ዩዘሮች በአጠቃላይ ወይም በመታወቂያቸው መፈለግ ይቻላል