#%RAML 1.0 DocumentationItem
title: Craft-Software-Online-Shopping-API-Specification
content: This is Craft-Software-Online-Shopping-API-Specification to CREATING PRODUCTS,USERS,ORDERS AND CATAGORIES RESOURCES FOR CRAFTSOFTWARE SHOPPING.