#%RAML 1.0 Overlay
extends: online-shopping.raml
title: overlay
usage: To provide user documentation and description |ይሄ ለተጠቃሚዎች በአማርኛ ቋንቋ ማብራሪያና መግለጫ ይሰጣል
documentation:
  - title 
    content: 
      This document defines the interface used in the RAML | ይህ ሰነድ RAML ውስጥ ጥቅም ላይ የዋለውን በደንብ ይገልጻል
      users: contains resource users | /ተጠቃሚዎች: ስለ ተጠቃሚዎች መርጃ  
      orders: contains resource orders | /ትዕዛዞች፡ ስለ የሚታዘዙ ነገሮች መርጃ 
      categories: contains resource categories | /ምድቦች፡ ስለ ምድቦችን መርጃ 
      products: contains resource product | /ምርቶች: ስለ ምርቶች መርጃ 
  

  
