#%RAML 1.0 AnnotationTypeDeclaration
properties:
  usage:
    description: understanding our api
    default: get
  controller:
    properties:
      protocol:
        description: the api u
        default: 
      url:
        description: group-bproject.net/
        default: 
      mediaType:
        description: can the user all http method?
        type: boolean
        default: false
      adminmediaType:
        description: can the user all http method?
        type: boolean
        default: true


