#%RAML 1.0 NamedExample
                [{ 
                   "categoryid": 11,
                   "name": "laptops"
                 },
                 {
                    "categoryid": 12,
                    "name": "home electronics"
                 },
                 {
                    "categoryid": 13,
                    "name": "mouse"
                 }]