#%RAML 1.0 NamedExample
                {
                  "orderid": 51,
                  "userid": 1,
                  "addressid": 201,
                  "discountid": 6,
                  "created": "2019-05-15 12:39:30",
                  "modified": "2019-05-15 15:39:30",
                  "status": "shipped",
                  "amount": 550
                }