#%RAML 1.0 Overlay
extends: Gruoup-B project.raml
usage: Gives a high-level overview on the end points of the shopping platform
documentation:
  - title: abc-two overlay
    content: Contains end point resources of products listed
    products: Contains an returns list of products on products database
    users: Contains an returns list of users on users database
    orders: Contains an returns list of orders on orders database
    categories: Contains an returns list of categories on categories database
