#%RAML 1.0 NamedExample
  [{
     "productid": 2,
      "categoryid": 16,
      "name": "DELL PC",
      "description": "CORE I 7",
      "video_url": "WWW.DELL.COM",
      "price": 2500
    },
    {
       "productid": 3,
       "categoryid": 17,
       "name": "DELL PC",
       "description": "CORE I 7",
       "video_url": "WWW.DELL.COM",
        "price": "abebe"
    }
    ]