#%RAML 1.0 SecurityScheme
type: OAuth 2.0
description: Gruoup-B project API authentication and authorization Scheme
describedBy:
  headers:
    Authorization:
      description: User authentication
      type: string
  responses:
    200:
      body:
        application/json:
          example: 
            message: You are authorized
    401:
      body:
        application/json:
          example:
            message: Un-authorized access
    403:
      body:
        application/json:
          example:
            message: Forbiden
      
