#%RAML 1.0 DataType
properties:
  AddLine1:
    type: string
  AddLine2:
    type: string
  country:
    type: string 
    default: 'USA'
  State:
    type: string
    maxLength: 2
  Zipcode: 
   type: number
   