#%RAML 1.0 ResourceType
get:
  description: resource <<resourcePathName>> not found 
  responses:
    404:
      body:
        application/json:
          example: {message: "<<resourcePath>> not found!"}