#%RAML 1.0 Overlay
extends: craft-online-shopping.raml
title: Craft-Online-Shopping overview
documentation:
  - title: overview
    content: the document define about the online shopping
    /product: 
usage: 
  to provide addtional info about the rest api for Spanish
description: 
