#%RAML 1.0 Trait
responses:
  200:
    description: unauthorized <<resourcePathName>>
    body:
      application/json:
        example:  {
                    message: "deleted"
                  }
  
