#%RAML 1.0 NamedExample
{ 
    "orderid": 100,
    "userid": 123,
    "addressid": "777",
    "discountid": 22,
    "created": "01-01-2021",
    "modified": "02-04-2021",
    "status": "shipped",
    "amount": 300
  }


