#%RAML 1.0 NamedExample
[ {
  "productName": "Dell laptop",
  "numberOf_prod": 5,
  "productid": 46,
  "payment": {
  "card_type": "VISA",
  "name": "mark ",
  "cardNumber": 1234567,
  "expirationDate": 2015-05-23
 } 

}
]