#%RAML 1.0 NamedExample
example:
  [
{"catagory_id": 10,
"description": 'dell laptop',
"name": 'dell laptop',
"price": 1000,
"productid": 101,
"video_url": "http://test.com/dell-laptop"},
{"catagory_id": 10,
"description": 'dell laptop',
"name": 'dell laptop',
"price": 1000,
"productid": 101,
"video_url": "http://test.com/dell-laptop"}
]