#%RAML 1.0 NamedExample
userResponse:
 {"firstName": "George",
"lastName": "Danny",
"email": "george@gmail.com",
"phone": "202-234-8978",
"Address": {
     "AddLine1": "546 forst st. NE",
     "AddLine2": " 546 forst st. Nw ",
     "country": "Ethiopia",
     "State": "VA",
     "Zipcode": 23444 

},

}

