#%RAML 1.0 NamedExample
ordersExample:
  [
  { 
    "orderid": 100,
    "userid": 123,
    "addressid": "777",
    "discountid": 22,
    "created": "01-01-2021",
    "modified": "02-04-2021",
    "status": "shipped",
    "amount": 300
  },

  {
    "orderid": 200,
    "userid": 345,
    "addressid": "888",
    "discountid": 33,
    "created": "02-01-2021",
    "modified": "02-02-2021",
    "status": "delivered",
    "amount": 400
  }
  ]