#%RAML 1.0 NamedExample

  {
    "productid": 1,
    "categoryid": 8,
    "name": "iPhone 12 Pro",
    "price": 999,
    "description": "A14 Bionic chip, Next‑generation Neural Engine",
    "url": "https://www.apple.com/iphone/" 
    }