#%RAML 1.0 NamedExample
productsExample:
  [
  {
  "productid": 1,
  "categoryid": 8,
  "name": "iPhone 12 Pro",
  "price": 999,
  "description": "A14 Bionic chip, Next‑generation Neural Engine",
  "url": "https://www.apple.com/iphone/" 
  },
  {
    "productid": 2,
    "categoryid": 4,
    "name": "Laptop", 
    "description": "personal computers",
    "price": 700,
    "url": "https://www.amazon.com/sony-laptop/s?k=sony+laptop"
  },

  {
    "productid": 3,
    "categoryid": 5,
    "name": " iPad Pro",   
    "description": "apple idevice",
    "price": 799,
    "url": "https://www.apple.com/ipad/"
  },

  {
    "productid": 4,
    "categoryid": 6,
    "name": "Mac", 
    "description": "idevice",
    "price": 999,
    "url": "https://www.apple.com/mac/' "
  }
  ]