#%RAML 1.0 NamedExample
usersExample:
  [
    {"userid": 1, "username": "yoni", "email": "yoni@gmail.com"},
    {"userid": 2, "username": "Dave", "email": "dave@gmail.com"},
    {"userid": 3, "username": "kal", "email": "kal@gmail.com"}
]
