  [
    {
   
    "username": "yoni",
    "email": "yoni@gmail.com",
        
    },
    {
   
    "username": "Dave",
    "email": "dave@gmail.com",
    
    
    },

    {
    
    "email": "kal@gmail.com",
    "username": "Kalie"
    },

    {
      
    "username": "Meri",
    "email": "mer@gmail.com",
    
    },

    {
    
    "username": "Selam",
    "email": "sel@gmail.com",
    
    
    },
    {
 
    "username": "Meri",
    "email": "mer@yahoo.com",
  
    
    }
  ]