#%RAML 1.0 ResourceType
post:
    #description: post list of resource <<resourcePathName>>
  responses:
    201: 
      body:
        application/json:
          type: <<post-resource>>
          example: <<exampleReference>> 


  