#%RAML 1.0 DataType
type: object
properties:
  orderid: 
    type: integer
    required: true
  userid: integer
  addressid: string
  discountid: integer
  created: string
  modified: string
  status: string
  amount: integer
  quantity: integer
