#%RAML 1.0 DataType

type: object
properties:
  productid: 
    type: integer
    required: true
  categoryid: 
   type: integer
   required: false
  name: 
   type: string
  description: 
   type: string
  url: 
   type: string
  price: 
   type: integer

  
