#%RAML 1.0 DataType
type: object
properties:
  orderid:
    type: integer
  userid:
    type: integer
  addressid:
    type: integer
  discountid:
    type: integer
  created:
    type: string
  modified:
    type: string
  status:
    type: string
  amount:
    type: integer
  